version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: safedriving-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_driver_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
